apiVersion: argoproj.io/v1alpha1  #crd
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OzShwartz/gh-k8s-agroCD.git'
    targetRevision: HEAD
    path: helm-charts/mongoapp
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
